
name: generate snake game
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: vivekteja0308-007
          outputs: |
            dist/github-snake.svg?color_snake=%23A855F7&color_dots=%23161B22,%231E1B4B,%234C1D95,%237C3AED,%23A855F7&color_background=%230D1117
            dist/github-snake-dark.svg?color_snake=%2322D3EE&color_dots=%23161B22,%23164E63,%230E7490,%2306B6D4,%2322D3EE&color_background=%230D1117
      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}